version: '3.8'

services:
  db_userprofile:
    image: postgres:13
    container_name: db_userprofile
    environment:
      POSTGRES_DB: db_userprofile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_userprofile:/var/lib/postgresql/data
    networks:
      - default

  db_email:
    image: postgres:13
    container_name: db_email
    environment:
      POSTGRES_DB: db_email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_email:/var/lib/postgresql/data
    depends_on:
      - db_userprofile
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    depends_on:
      - db_email
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq 
    networks:
      - default
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 10s

  ms-user-profile:
    build:
      context: ./src-ms-user-profile
    container_name: ms-user-profile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_userprofile:5432/db_userprofile
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - KAFKA_PORTOUT_TOPIC=createduser.notification
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db_userprofile
      - kafka
      - rabbitmq
    networks:
      - default

  ms-email:
    build:
      context: ./ms-email
    container_name: ms-email
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_email:5432/db_email 
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - KAFKA_PORTIN_TOPIC=createduser.notification
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - RABBIT_QUEUE_NAME=ms.email
      - RABBIT_SERVER_HOST=rabbitmq
      - RABBIT_SERVER_USERNAME=guest
      - RABBIT_SERVER_PASSWORD=guest
      - GOOGLE_MAIL_USERNAME=iluizfranca@gmail.com
      - GOOGLE_MAIL_PASSWORD=nfhbbipomaeomhif
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - default

volumes:
  postgres_data_userprofile:
  postgres_data_email:
  rabbitmq-data: 

networks:
  default:
    driver: bridge
