spring:
  application:
    name: test-db
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_test
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
server:
  servlet:
    context-path: "/api"
  port: 8083

logging:
  level:
    web: debug

